# Generated by Django 5.0.3 on 2024-03-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotafiles', '0002_rename_uploaded_at_uploadedfile_upload_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
