# Generated by Django 5.0.3 on 2024-05-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotafiles', '0006_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='received_datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='report',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
