# Generated by Django 5.0.3 on 2024-06-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotafiles', '0009_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_by',
        ),
    ]
