# Generated by Django 5.0.3 on 2024-06-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_otp_url_customuser_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secret_key',
        ),
    ]
